### ISSUE TITLE
Skip sending reports instead of throwing exception

### ISSUE THREAD

**Issue by eugene-manuilov** [ngraf/slack-codeception-extension#8]
If i set `webhook` option to be empty string, your extension throws `ExtensionException` and it crashes tests run. Instead of doing it, your extension needs to skip sending reports to slack.

**Comment by ngraf** [comment]
That behaviour is discussable.

I throw this exception on purpose because if you decide to usethis extension and you enabled it, then a webhook is required and _(A)_ I want to point this out clearly to the user of my extension.

I totally agree with your usecase, that you want to configure the extension in general, but occassionally you don't want to use it in some testruns, so you decided to remove the webhook.

What I rather recommend to do is the following (this is how I do it in general):

1) **Remove** the following part of your `codeception.yml`: 

```
extensions:
  enabled:
    - Codeception\Extension\SlackExtension
```

2a) When you do **not want to send** Slack messages just run:

````
$ codecept run
````

2b) When you **want to send** Slack messages run:

```
$ codecept run --ext SlackExtension
```

What do you think? Are you happy with my suggestion? I don't want to lose the _(A)_ behaviour.

**Comment by ngraf** [comment]
Issue closed due to inactivity.

I still think what you reported is rather a feature than an issue.
